### ISSUE TITLE
Unable to See Tooltip while hovering over Truncated text in Table Header

### ISSUE THREAD

**Issue by srikant-ch5** [elyra-ai/canvas#1859] opened 2024-04-10 13:29 UTC
After opening Conditions_paramDef.json and trying to click on More Tables > Configure Dummy Types when I hover on Override tooltip is not showing up.

https://github.com/elyra-ai/canvas/assets/16302714/b7d09717-4a4f-4aa6-afb8-1609d00c3141

When I try to do the same in textfield_paramDef.json I am able to see the tooltip.

**Comment by nmgokhale** [comment] 2024-04-11 17:34
@srikant-ch5 Please create a git issue in internal tracking repo and link this issue there. Thanks

**Comment by nmgokhale** [comment] 2024-05-28 17:22
This issue is duplicate of https://github.com/elyra-ai/canvas/issues/1981. Issue is fixed in PR https://github.com/elyra-ai/canvas/pull/1982. 

Closing this issue.

**Closed by nmgokhale** 2024-05-28 17:22 UTC
Labels: Bug, Properties
