### ISSUE TITLE
Canvas lags and uses lots of CPU when rendering a super_node in a super_node

### ISSUE THREAD

**Issue by ajbozarth** [elyra-ai/canvas#721] opened 2021-07-22 16:01 UTC
While working on a pipeline in Elyra I created a super_node inside a super_node and my instance Elyra started to lag and hang and become unusable. According to my Activity Monitor that tab of Safari was using over 80% of a CPU. It seems nested super_nodes consume an exponential amount of CPU.

**Comment by tomlyn** [comment] 2021-07-22 16:11
@ajbozarth Hi Alex -- Can you provide the JSON for the pipeline flow you are providing to common-canvas that is causing the problem please?  Do you see a similar problem on Chrome and/or Firefox?

**Comment by ajbozarth** [comment] 2021-07-22 16:24
I did not check on other browsers, and here's the file: 
[v3-Copy1.pipeline.zip](https://github.com/elyra-ai/canvas/files/6863786/v3-Copy1.pipeline.zip)

**Comment by tomlyn** [comment] 2021-07-22 16:54
@ajbozarth I just tried it with the test harness and that file comes up almost instantaneously on Safari on my Mac. I can navigate into and out of the sub-flows very quickly and I don't see an extraordinary CPU usage. 
Can you try a similar experiment on your machine? Here's what you need to do : 
1. Open the test harness: https://wdp-common-canvas-dev.stage1.mybluemix.net/#/
2. Click the hamburger icon (tooltip is 'Common Canavs') in the top right corner
3. Under Canvas Diagram click 'Choose an option' then in the menu click 'Choose from Location'
4. Click the 'Choose FIle'  button and then select the file you sent to me.
5. The name of the file should appear in the test harness panel, then click "Submit"
The flow should appear in your browser.

**Comment by ajbozarth** [comment] 2021-07-22 21:13
following those steps there's no lag, but the lag was mostly caused when creating the super_nodes which I couldn't test there because Create Supernode wasn't in the context menu

**Comment by tomlyn** [comment] 2021-07-22 22:32
The 'Create Supernode' context menu option is available in the test harness.  You need to select a single node or contiguous nodes for it to appear. (See below).

I suspect you will find it works reasonably quickly. If so that  suggests the problem is not in common-canvas and perhaps something is going on in the application code that is calling common-canvas. 

![Jul-22-2021 15-27-51](https://user-images.githubusercontent.com/15114439/126717252-f628f1c8-0969-446e-810b-2cb3e6d8783d.gif)

**Comment by tomlyn** [comment] 2021-07-30 06:04
@ajbozarth Hi Alex -- Any news on this? Have you investigated further? Can this be closed?

**Comment by ajbozarth** [comment] 2021-07-30 15:33
Given this is not a blocker for the Elyra 3.0 release I have not had time to look into it further. I personally only ran into it while working on a edge test case

**Comment by tomlyn** [comment] 2021-07-30 17:17
OK I'll close it. If you get time to investigate and can provide a bunch of steps that will reproduce the problem it can be reopened.

**Closed by tomlyn** 2021-07-30 17:17 UTC
Labels: Canvas
