### ISSUE TITLE
Elyra v13.0.0-alpha.0 broken tests

### ISSUE THREAD

**Issue by vladbalanescu** [elyra-ai/canvas#1838] opened 2024-04-05 09:15 UTC
Ref: #3749

Bug:
---
RTL tests ran with jest are broken in the latest Elyra v13.0.0-alpha.0. Because a new dependency was introduced on `redux`, the consumers of this library, now need to make sure that they have a custom `transformIgnorePatternRule` in jest, since redux is distributed as `cjs`.
![image (2)](https://github.com/elyra-ai/canvas/assets/25124000/1f172551-5bbf-4ad7-b879-84337b45d10b)

Workaround:
---
```
   "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|cjs|jsx|ts|tsx)$",
      "^.+\\.module\\.(css|sass|scss)$"
  ] 
```

Acceptance crtieria:
---
- [ ] The above workaround is documented in the version's release notes at the very least

**Comment by nmgokhale** [comment] 2024-04-11 19:07
`combineReducers` is imported from `redux` package. `redux` version was recently upgraded from `4.0.5` to [5.0.1](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/package.json#L51). 

`node_modules/redux` folder structure in v4.0.5  -
![Screenshot 2024-04-11 at 11 56 18 AM](https://github.com/elyra-ai/canvas/assets/25124000/927ed1c0-9443-4977-b725-a40451a0ce2d)


`node_modules/redux` folder structure in v5.0.1 - 
`cjs` folder was added under `dist`. 
![Screenshot 2024-04-11 at 12 01 35 PM](https://github.com/elyra-ai/canvas/assets/25124000/84211800-7af1-4734-885c-c46a84210d4b)

However, we have several unit tests which initialize [canvasController = new CanvasController();](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/__tests__/common-canvas/common-canvas-test.js#L33) and all the tests run okay with `redux 5.0.1. `

@vladbalanescu The error you're seeing might be related to jest or babel config issue in your project.
 I didn't find `babel.config.json` file in your project. Can you try these steps to see if it fixes your test -
- Remove above workaround from your `package.json` file
- Add this [babel.config.json](https://github.com/elyra-ai/canvas/blob/main/canvas_modules/common-canvas/babel.config.json) file under `/cp4i-canvas`. It should be at the same level as package.json file
- Try running your test again

**Comment by nmgokhale** [comment] 2024-04-15 19:02
@vladbalanescu Any update on this issue?

**Comment by vladbalanescu** [comment] 2024-04-17 08:36
@nmgokhale For this repo, we don't have dedicated jest/babel config files, that is specified directly in `package.json`. The solution you're suggesting is already present in that file, here is the code:
```json
...
  "babel": {
    "presets": [
      "@babel/preset-env",
      [
        "@babel/preset-react",
        {
          "runtime": "automatic"
        }
      ]
    ],
    "plugins": [
      "@babel/plugin-transform-runtime",
      "@babel/plugin-proposal-export-default-from",
      "inline-react-svg"
    ]
  },
```

**Comment by matthoward366** [comment] 2024-04-17 11:20
@vladbalanescu The problem is we don't see this problem in our testing and don't need to add the `transformIgnorePatterns` option.  We think it's because in our case jest is picking up the correct babel configuration and in your environment it's probably using the default.  It might be that there is more than 1 way to solve this issue.

**Comment by nmgokhale** [comment] 2024-04-19 17:57
Closing this as a test config issue on consuming application side. No code change needed in elyra canvas.

**Closed by nmgokhale** 2024-04-19 17:57 UTC
